### ISSUE TITLE
Requests is required but doesn't unpack with pip installation

### ISSUE THREAD

**Issue by dyspop** [dyspop/responsysrest#3]
```
$pip install git+https://{auth_token}:x-oauth-basic@github.com/dyspop/responsysrest.git@0.1.7
Collecting git+https://{auth_token}:x-oauth-basic@github.com/dyspop/responsysrest.git@0.1.7
  Cloning https://{auth_token}:x-oauth-basic@github.com/dyspop/responsysrest.git (to 0.1.7) to /private/var/folders/p4/~/T/pip-QOqLPX-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/p4/~/T/pip-QOqLPX-build/setup.py", line 4, in <module>
        import responsysrest
      File "responsysrest/__init__.py", line 3, in <module>
        from .client import Client
      File "responsysrest/client.py", line 3, in <module>
        import requests
    ImportError: No module named requests
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/p4/~/T/pip-QOqLPX-build/
```

```
$pip install requests
Collecting requests
  Using cached requests-2.18.4-py2.py3-none-any.whl
Requirement already satisfied: idna<2.7,>=2.5 in ./env/lib/python2.7/site-packages (from requests)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./env/lib/python2.7/site-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python2.7/site-packages (from requests)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./env/lib/python2.7/site-packages (from requests)
Installing collected packages: requests
Successfully installed requests-2.18.4
```

```
$pip install git+https://{auth_token}:x-oauth-basic@github.com/dyspop/responsysrest.git@0.1.7
Collecting git+https://{auth_token}:x-oauth-basic@github.com/dyspop/responsysrest.git@0.1.7
  Cloning https://{auth_token}:x-oauth-basic@github.com/dyspop/responsysrest.git (to 0.1.7) to /private/var/folders/p4/~/T/pip-QOqLPX-build
Requirement already satisfied: requests in ./env/lib/python2.7/site-packages (from responsysrest==0.1.7)
Requirement already satisfied: idna<2.7,>=2.5 in ./env/lib/python2.7/site-packages (from requests->responsysrest==0.1.7)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./env/lib/python2.7/site-packages (from requests->responsysrest==0.1.7)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python2.7/site-packages (from requests->responsysrest==0.1.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./env/lib/python2.7/site-packages (from requests->responsysrest==0.1.7)
Installing collected packages: responsysrest
  Running setup.py install for responsysrest ... done
Successfully installed responsysrest-0.1.7
```

**Comment by dyspop** [comment]
Redoing setup.py fixed this issue inadvertently.
